"""class roster prefix

Revision ID: 3443629b0ff3
Revises: b5ffe863979f
Create Date: 2026-08-13 05:19:23.933315

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3443629b0ff3'
down_revision: Union[str, Sequence[str], None] = 'b5ffe863979f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    with op.batch_alter_table('classes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('roster_prefix', sa.String(length=20), server_default='', nullable=False))

    # Lớp đã tồn tại thì đóng băng tiền tố ở đúng mã hiện tại: mã ẩn danh trong
    # những bản thầy cô đã tải về được dựng từ mã lớp, nên phải giữ nguyên kể cả
    # sau khi lớp đó đổi mã.
    op.execute("UPDATE classes SET roster_prefix = class_code WHERE roster_prefix = ''")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('classes', schema=None) as batch_op:
        batch_op.drop_column('roster_prefix')

    # ### end Alembic commands ###
