"""journal entry belongs to a class

Revision ID: 562266241b11
Revises: 9a1c4e2b7d15
Create Date: 2026-08-13 10:52:40.855015

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '562266241b11'
down_revision: Union[str, Sequence[str], None] = '9a1c4e2b7d15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema.

    Bài đã có từ trước nhận NULL, nghĩa là "việc cá nhân" — không giáo viên nào
    đọc được. Cố ý hỏng về phía an toàn: không có cách nào suy ngược ra bài cũ
    thuộc lớp nào, và đoán sai theo hướng còn lại là để một người lớn đọc được
    thứ đáng lẽ không được đọc.
    """
    with op.batch_alter_table('journal_entries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('class_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_journal_entries_class_id'), ['class_id'], unique=False)
        # SQLite chạy batch mode nên khoá ngoại bắt buộc phải có tên; để None
        # thì alembic dừng giữa chừng với "Constraint must have a name".
        batch_op.create_foreign_key(
            "fk_journal_entries_class_id_classes", "classes", ["class_id"], ["id"]
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('journal_entries', schema=None) as batch_op:
        batch_op.drop_constraint("fk_journal_entries_class_id_classes", type_="foreignkey")
        batch_op.drop_index(batch_op.f('ix_journal_entries_class_id'))
        batch_op.drop_column('class_id')

    # ### end Alembic commands ###
