"""baseline schema

Revision ID: 7dd9304abf3e
Revises: 
Create Date: 2026-08-12 11:04:27.352416

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7dd9304abf3e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.String(length=40), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('reported_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('schools',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ten', sa.String(length=160), nullable=False),
    sa.Column('tinh_thanh', sa.String(length=80), nullable=False),
    sa.Column('ma_giao_vien', sa.String(length=20), nullable=True),
    sa.Column('ma_het_han', sa.DateTime(), nullable=True),
    sa.Column('hoat_dong', sa.Boolean(), nullable=False),
    sa.Column('doi_tac_tu', sa.Date(), nullable=True),
    sa.Column('lien_he_ten', sa.String(length=120), nullable=False),
    sa.Column('lien_he_email', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ma_giao_vien')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('avatar_id', sa.String(length=40), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('oauth_provider', sa.String(length=20), nullable=True),
    sa.Column('oauth_sub', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('password_changed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_oauth_sub'), ['oauth_sub'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_school_id'), ['school_id'], unique=False)

    op.create_table('badges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('badge_type', sa.String(length=60), nullable=False),
    sa.Column('earned_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('badges', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_badges_student_id'), ['student_id'], unique=False)

    op.create_table('classes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('class_code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('class_code')
    )
    with op.batch_alter_table('classes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_classes_school_id'), ['school_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_classes_teacher_id'), ['teacher_id'], unique=False)

    op.create_table('consents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('loai', sa.String(length=30), nullable=False),
    sa.Column('phien_ban', sa.String(length=20), nullable=False),
    sa.Column('dong_y_luc', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('consents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_consents_user_id'), ['user_id'], unique=False)

    op.create_table('guided_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('scenario_id', sa.String(length=80), nullable=False),
    sa.Column('stage_index', sa.Integer(), nullable=False),
    sa.Column('beat_index', sa.Integer(), nullable=False),
    sa.Column('finished', sa.Boolean(), nullable=False),
    sa.Column('synthesis', sa.Text(), nullable=False),
    sa.Column('transcript', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('guided_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_guided_sessions_scenario_id'), ['scenario_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_guided_sessions_student_id'), ['student_id'], unique=False)

    op.create_table('journal_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('scenario_id', sa.String(length=80), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=240), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('ai_transcript', sa.Text(), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=False),
    sa.Column('video_url', sa.String(length=500), nullable=False),
    sa.Column('submitted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('journal_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_journal_entries_student_id'), ['student_id'], unique=False)

    op.create_table('password_resets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('password_resets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_password_resets_token_hash'), ['token_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_password_resets_user_id'), ['user_id'], unique=False)

    op.create_table('yeu_cau_xoa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ly_do', sa.Text(), nullable=False),
    sa.Column('tao_luc', sa.DateTime(), nullable=False),
    sa.Column('xu_ly_luc', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('yeu_cau_xoa', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_yeu_cau_xoa_user_id'), ['user_id'], unique=False)

    op.create_table('assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('scenario_id', sa.String(length=80), nullable=True),
    sa.Column('field', sa.String(length=80), nullable=True),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assignments_class_id'), ['class_id'], unique=False)

    op.create_table('class_memberships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('class_memberships', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_class_memberships_class_id'), ['class_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_class_memberships_student_id'), ['student_id'], unique=False)

    op.create_table('feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('journal_entry_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['journal_entry_id'], ['journal_entries.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_feedback_journal_entry_id'), ['journal_entry_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_feedback_student_id'), ['student_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_feedback_teacher_id'), ['teacher_id'], unique=False)

    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=True),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=240), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('field', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_class_id'), ['class_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_student_id'), ['student_id'], unique=False)

    op.create_table('portfolio_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('journal_entry_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('shared', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['journal_entry_id'], ['journal_entries.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('portfolio_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_portfolio_entries_journal_entry_id'), ['journal_entry_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_portfolio_entries_student_id'), ['student_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('portfolio_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_portfolio_entries_student_id'))
        batch_op.drop_index(batch_op.f('ix_portfolio_entries_journal_entry_id'))

    op.drop_table('portfolio_entries')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_student_id'))
        batch_op.drop_index(batch_op.f('ix_notifications_class_id'))

    op.drop_table('notifications')
    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_feedback_teacher_id'))
        batch_op.drop_index(batch_op.f('ix_feedback_student_id'))
        batch_op.drop_index(batch_op.f('ix_feedback_journal_entry_id'))

    op.drop_table('feedback')
    with op.batch_alter_table('class_memberships', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_class_memberships_student_id'))
        batch_op.drop_index(batch_op.f('ix_class_memberships_class_id'))

    op.drop_table('class_memberships')
    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assignments_class_id'))

    op.drop_table('assignments')
    with op.batch_alter_table('yeu_cau_xoa', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_yeu_cau_xoa_user_id'))

    op.drop_table('yeu_cau_xoa')
    with op.batch_alter_table('password_resets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_password_resets_user_id'))
        batch_op.drop_index(batch_op.f('ix_password_resets_token_hash'))

    op.drop_table('password_resets')
    with op.batch_alter_table('journal_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_journal_entries_student_id'))

    op.drop_table('journal_entries')
    with op.batch_alter_table('guided_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_guided_sessions_student_id'))
        batch_op.drop_index(batch_op.f('ix_guided_sessions_scenario_id'))

    op.drop_table('guided_sessions')
    with op.batch_alter_table('consents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_consents_user_id'))

    op.drop_table('consents')
    with op.batch_alter_table('classes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_classes_teacher_id'))
        batch_op.drop_index(batch_op.f('ix_classes_school_id'))

    op.drop_table('classes')
    with op.batch_alter_table('badges', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_badges_student_id'))

    op.drop_table('badges')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_school_id'))
        batch_op.drop_index(batch_op.f('ix_users_oauth_sub'))

    op.drop_table('users')
    op.drop_table('schools')
    op.drop_table('reports')
    # ### end Alembic commands ###
