"""unassign restore edit and resume columns

Revision ID: f8a19f902c1b
Revises: 562266241b11
Create Date: 2026-08-21 14:01:47.517777

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8a19f902c1b'
down_revision: Union[str, Sequence[str], None] = '562266241b11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('archived_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    # `guided_sessions.updated_at` là NOT NULL, mà bảng có thể đã có dữ liệu —
    # thêm thẳng cột NOT NULL không mặc định là hỏng ngay. Thêm cho phép rỗng,
    # điền bằng `created_at` (hoạt động đã biết gần nhất tính tới lúc này), rồi
    # mới siết lại.
    with op.batch_alter_table('guided_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    op.execute("UPDATE guided_sessions SET updated_at = created_at WHERE updated_at IS NULL")

    with op.batch_alter_table('guided_sessions', schema=None) as batch_op:
        batch_op.alter_column('updated_at', existing_type=sa.DateTime(), nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guided_sessions', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.drop_column('archived_at')

    # ### end Alembic commands ###
